backend:
  name: github
  repo: justynaklewicka/petsitter-site
  branch: main
  base_url: https://decap-cms-oauth.vercel.app
  auth_endpoint: /api/auth

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Strony"
    files:
      - file: "src/pages/index.md"
        label: "Strona główna"
        name: "index"
        fields:
          - { label: "Tytuł", name: "title", widget: "string" }
          - { label: "Treść", name: "body", widget: "markdown" }

      - file: "src/pages/o-mnie.md"
        label: "O mnie"
        name: "o-mnie"
        fields:
          - { label: "Tytuł", name: "title", widget: "string" }
          - { label: "Treść", name: "body", widget: "markdown" }

      - file: "src/pages/uslugi.md"
        label: "Cennik i Usługi"
        name: "uslugi"
        fields:
          - { label: "Tytuł", name: "title", widget: "string" }
          - { label: "Treść", name: "body", widget: "markdown" }

      - file: "src/pages/galeria.md"
        label: "Galeria"
        name: "galeria"
        fields:
          - { label: "Tytuł", name: "title", widget: "string" }
          - label: "Zdjęcia"
            name: "images"
            widget: "list"
            fields:
              - { name: "src", label: "Zdjęcie", widget: "image" }
              - { name: "caption", label: "Podpis", widget: "string", required: false }
          - { label: "Treść", name: "body", widget: "markdown" }

      - file: "src/pages/kontakt.md"
        label: "Kontakt"
        name: "kontakt"
        fields:
          - { label: "Tytuł", name: "title", widget: "string" }
          - { label: "Treść", name: "body", widget: "markdown" }

